import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { PhotoUpload } from '../components/PhotoUpload/PhotoUpload';

import styles from './Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles['main-wrapper']}>
      <div className={styles['main-header']}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <main className={styles['main-container']}>
        <PhotoUpload />
      </main>

      <footer className={styles['main-footer']}>
        <h2>Disclaimer</h2>
        <small>
          Uploaded files are discarded right after they have been processed (resized, cropped, composited) and will not
          be used for anything else than providing the user with a modified image of their choice.
        </small>
      </footer>

      <div className={styles['forkme-ribbon']}>
        <a href="https://github.com/janjaap/linkedin-badge">Fork me on GitHub</a>
      </div>
    </div>
  );
};

export default Home;
