import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { PhotoUpload } from '../components/PhotoUpload/PhotoUpload';

import styles from './Home.module.css';

const Home: NextPage = () => (
  <div className={styles['main-wrapper']}>
    <header className={styles['main-header']}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Linkedin profile badge generator</h1>

      <div className={styles['links-banner']}>
        <a href="https://github.com/janjaap/linkedin-badge" title="Check out the code">
          <Image src="/octocat.png" width={32} height={32} alt="" />
        </a>

        <a href="https://www.linkedin.com/in/janjaapvandeursen/" title="My Linkedin profile">
          <Image src="/in.png" width={32} height={32} alt="" />
        </a>
      </div>
    </header>

    <main className={styles['main-container']}>
      <PhotoUpload />
    </main>

    <footer className={styles['main-footer']}>
      <h2>Disclaimer</h2>
      <p>
        <small>
          The information provided by JJVD.net (&lsquo;we&rsquo;, &lsquo;us&rsquo;, or &lsquo;our&rsquo;) on{' '}
          <Link href="https://linkedin-badge.vercel.app/">https://linkedin-badge.vercel.app/</Link> (the
          &lsquo;Site&rsquo;) is for general informational purposes only. All information on the Site is provided in
          good faith, however we make no representation or warranty of any kind, express or implied, regarding the
          accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site. UNDER
          NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF
          THE USE OF THE SITE OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SITE. YOUR USE OF THE SITE AND YOUR
          RELIANCE ON ANY INFORMATION ON THE SITE IS SOLELY AT YOUR OWN RISK.
        </small>
      </p>
      <p>
        <small>
          Uploaded files are discarded right after they have been processed (resized, cropped, composited) and will not
          be used for anything else than providing the user with a modified image of their choice.
        </small>
      </p>

      <p>
        <small>
          For suggestions, remarks, issues, please refer to{' '}
          <Link href="https://github.com/janjaap/linkedin-badge/issues">the issues page in the Github repository</Link>.
        </small>
      </p>
    </footer>
  </div>
);

export default Home;
